version: '3.9'
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: pharma
      POSTGRES_PASSWORD: pharma
      POSTGRES_DB: pharma
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    command: redis-server --appendonly yes
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:
